apiVersion: apps/v1
kind: Deployment
metadata:
  name: reflex-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reflex-simulator
  template:
    metadata:
      labels:
        app: reflex-simulator
    spec:
      containers:
      - name: reflex-sim
        image: gcr.io/bubbly-mission-478719-h6/simple-reflex-simulator:{{IMAGE_TAG}}
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: reflex-service
spec:
  selector:
    app: reflex-simulator
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80          # External port to access
      targetPort: 5000  # Container port